version: '3.8'
services:
  # Оригинальный сайт (в корне)
  original:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  # MITM-атака
  mitm-attack:
    build:
      context: ./mitm-attack
    ports:
      - "8081:8081"
    depends_on:
      - original