version: '3.8'
services:
  original:
    build:
      context: ./original
    networks:
      - mitm-network

  mitm-attack:
    build:
      context: ./mitm-attack
    ports:
      - "8080:8081" 
    networks:
      - mitm-network

networks:
  mitm-network:
    driver: bridge